DROP SEQUENCE customer_seq;
DROP SEQUENCE account_seq;
DROP SEQUENCE transaction_seq;

CREATE SEQUENCE customer_seq
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE account_seq
START WITH 1001
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE transaction_seq
START WITH 1
INCREMENT BY 1
NOCACHE;
